#!/usr/bin/env python3
"""Pack the web viewer data and upload it to the "web-data" GitHub Release.

``web/public/data`` (generated by ``scripts/export_report_json.py --all``)
is no longer tracked in git: this script tar-gzips it into
``web-data.tar.gz`` — with archive paths rooted at ``web/public/data/`` so
the deploy workflow can extract it at the checkout root — and uploads it
to the ``web-data`` release via ``gh`` (asset is replaced with --clobber).

Usage:
    python scripts/publish_web_data.py                # pack + ensure release + upload
    python scripts/publish_web_data.py --dry-run      # pack only, print the gh commands
"""
from __future__ import annotations

import argparse
import shlex
import subprocess
import tarfile
from pathlib import Path

RELEASE_TITLE = "Web viewer data"
RELEASE_NOTES = "Auto-updated web viewer dataset"


def _dir_stats(data_dir: Path) -> tuple[int, int]:
    """(file count, total bytes) of *data_dir* (recursive)."""
    files = [f for f in data_dir.rglob("*") if f.is_file()]
    return len(files), sum(f.stat().st_size for f in files)


def build_tarball(data_dir: Path, tarball: Path) -> int:
    """Tar-gzip *data_dir* into *tarball* with fixed ``<data-dir>/...`` arcnames.

    Returns the number of files packed. Fixed arcnames (never absolute or
    ``../`` paths) are what let the workflow extract with ``tar -xzf`` from
    the repo root and land the files in ``web/public/data/``.
    """
    arc_root = data_dir.as_posix()
    files = sorted(f for f in data_dir.rglob("*") if f.is_file())
    with tarfile.open(tarball, "w:gz") as tar:
        for f in files:
            tar.add(f, arcname=f"{arc_root}/{f.relative_to(data_dir).as_posix()}")
    return len(files)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--data-dir", default="web/public/data",
                        help="Directory of generated web JSONs (default: web/public/data)")
    parser.add_argument("--tag", default="web-data",
                        help="GitHub Release tag to upload to (default: web-data)")
    parser.add_argument("--tarball", default="web-data.tar.gz",
                        help="Output tar.gz path (default: web-data.tar.gz)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Build the tarball but only print the gh commands (no network)")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    tarball = Path(args.tarball)
    if not data_dir.is_dir():
        print(f"Data directory not found: {data_dir} — "
              f"run `python scripts/export_report_json.py --all` first.")
        raise SystemExit(1)

    n_files, total = _dir_stats(data_dir)
    print(f"1. Packing {data_dir} ({n_files} files, {total / 1e6:.1f} MB) into {tarball} ...")
    packed = build_tarball(data_dir, tarball)
    print(f"   packed {packed} files -> {tarball} ({tarball.stat().st_size / 1e6:.1f} MB)")

    view_cmd = ["gh", "release", "view", args.tag]
    create_cmd = ["gh", "release", "create", args.tag,
                  "--title", RELEASE_TITLE, "--notes", RELEASE_NOTES]
    upload_cmd = ["gh", "release", "upload", args.tag, tarball.as_posix(), "--clobber"]

    if args.dry_run:
        print(f"2. Dry run — no network calls; commands that would run for tag {args.tag!r}:")
        print(f"   $ {shlex.join(view_cmd)}   # if this fails (no release yet):")
        print(f"   $ {shlex.join(create_cmd)}")
        print(f"   $ {shlex.join(upload_cmd)}")
        return

    print(f"2. Ensuring release {args.tag!r} exists ...")
    if subprocess.run(view_cmd, capture_output=True).returncode == 0:
        print(f"   release {args.tag!r} already exists")
    else:
        print(f"   release {args.tag!r} missing — creating ...")
        subprocess.run(create_cmd, check=True)

    print(f"3. Uploading {tarball.as_posix()} to release {args.tag!r} (--clobber) ...")
    subprocess.run(upload_cmd, check=True)
    print(f"   done: web viewer data published on release {args.tag!r}")


if __name__ == "__main__":
    main()
