import { useMemo, useRef, useState } from "react";
import { useJson } from "./api";
import { navigate, useRoute } from "./router";
import { ActionMenu, Button, ConfirmDialog, Dialog, EmptyState, InlineAlert, Loading, SeverityBadge, StatusBadge, absTime } from "./ui";
import { fieldLabel } from "./fieldLabels";
import type { BackendHealth } from "./health";
import type { Lang, Translate } from "./i18n";
import { addEvidence, addNote, createProject, deleteEvidence, deleteNote, deleteProject, isProjectDetail, isProjectList, removeAsset, updateNote, updateProject, type Project, type ProjectListItem } from "./projectApi";
import { REGISTRY_OPTIONS, savedStateToSearchState, searchStateToQuery } from "./searchState";
import ScopeHeader from "./ScopeHeader";
import { ActivityTrend, CategoryBreakdown, ChangeRow, FreshnessBadge, IntelligenceMetricStrip, PageSection, categoryLabel, type TrendBucket } from "./IntelligenceViz";
import { positivePage, projectTab, projectView, sourceTrialKey, stableProjectSort, trialView as parseTrialView, type ProjectTab } from "./phase4State";

type UpdateItem = { event_id: number; trial_id: string; source: string; title: string; field_name: string; severity: string; detected_at?: string; project_trial: boolean; project_monitors: string[]; old_value: string | null; new_value: string | null };
type Updates = { total: number; trial_count: number; items: UpdateItem[]; page: number; page_size: number; facets: { severities: Record<string, number> }; analytics?: { trends: TrendBucket[]; categories: Record<string, number> } };
type MatchTrials = { total: number; page: number; page_size: number; trials: Array<{ source: string; trial_id: string; title: string; monitors: string[] }> };
type Briefing = { summary: string; counts: Record<string, number>; sections: Array<{ key: string; count: number; items?: UpdateItem[] }>; freshness: { sources: Array<{ full_name: string; freshness: string }> } };
type Membership = { monitor_activity: Array<{ id: number; monitor_name: string; trial_id: string; event_type: string; detected_at: string }> };
const isUpdates = (v: unknown): v is Updates => typeof v === "object" && v !== null && Array.isArray((v as Updates).items);
const isMatchTrials = (v: unknown): v is MatchTrials => typeof v === "object" && v !== null && Array.isArray((v as MatchTrials).trials);
const isBriefing = (v: unknown): v is Briefing => typeof v === "object" && v !== null && typeof (v as Briefing).counts === "object";
const isMembership = (v: unknown): v is Membership => typeof v === "object" && v !== null && Array.isArray((v as Membership).monitor_activity);
const TABS: ProjectTab[] = ["overview", "trials", "activity", "intelligence", "notebook"];

export default function ProjectsPage({ health, t, lang }: { health: BackendHealth; t: Translate; lang: Lang }) {
  const route = useRoute();
  const id = route.segments[1] && /^\d+$/.test(route.segments[1]) ? Number(route.segments[1]) : 0;
  if (health.state !== "online") return <section className="page-main"><h1>{t("ws.projectsTitle")}</h1><InlineAlert tone="error" title={t("ws.projectsUnavailable")} /></section>;
  return id ? <ProjectDetail id={id} t={t} lang={lang} /> : <ProjectList t={t} />;
}

function ProjectList({ t }: { t: Translate }) {
  const route = useRoute();
  const view = projectView(route.query.get("view"), route.query.get("include_archived"));
  const q = route.query.get("q") ?? "";
  const [tick, setTick] = useState(0);
  const [editor, setEditor] = useState<{ mode: "create" | "rename"; project?: ProjectListItem } | null>(null);
  const [deleting, setDeleting] = useState<ProjectListItem | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [quickName, setQuickName] = useState("");
  const [quickDescription, setQuickDescription] = useState("");
  const list = useJson(`/api/projects?include_archived=true&refresh=${tick}`, isProjectList);
  const setQuery = (values: Record<string, string>) => { const next = new URLSearchParams(route.query); Object.entries(values).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); navigate(`/projects?${next}`); };
  const rows = useMemo(() => list.status === "ready" ? stableProjectSort(list.data.projects.filter((project) => (view === "archived") === Boolean(project.archived_at) && (!q.trim() || `${project.name} ${project.description}`.toLocaleLowerCase().includes(q.trim().toLocaleLowerCase())))) : [], [list, view, q]);
  const mutate = async (job: Promise<unknown>, after?: () => void) => { setBusy(true); setError(""); try { await job; setTick((v) => v + 1); after?.(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
  return <section className="page-main operations-page">
    <div className="page-head"><div><h1>{t("ws.projectsTitle")}</h1><p className="page-sub">{t("ws.projectsDescription")}</p></div><Button variant="primary" onClick={() => setEditor({ mode: "create" })}>{t("ws.openCreateProject")}</Button></div>
    <form className="saved-toolbar quick-project-create" onSubmit={(event) => { event.preventDefault(); if (quickName.trim()) mutate(createProject(quickName.trim(), quickDescription.trim()), () => { setQuickName(""); setQuickDescription(""); }); }}><label><span className="sr-only">{t("ws.projectName")}</span><input aria-label={t("ws.projectName")} placeholder={t("ws.projectName")} value={quickName} onChange={(event) => setQuickName(event.target.value)} required /></label><label><span className="sr-only">{t("ws.projectDescriptionLabel")}</span><input aria-label={t("ws.projectDescriptionLabel")} placeholder={t("ws.projectDescriptionInput")} value={quickDescription} onChange={(event) => setQuickDescription(event.target.value)} /></label><Button type="submit" variant="secondary" loading={busy}>{t("ws.newProject")}</Button></form>
    <div className="operations-toolbar"><label className="check-row"><input type="checkbox" aria-label={t("ws.showArchived")} checked={view === "archived"} onChange={(event) => setQuery({ view: event.target.checked ? "archived" : "active" })} />{t("ws.showArchived")}</label><div className="ui-segmented" role="radiogroup" aria-label={t("ws.projectViews")}><button role="radio" aria-checked={view === "active"} className={view === "active" ? "is-selected" : ""} onClick={() => setQuery({ view: "active" })}>{t("ws.activeProjects")}</button><button role="radio" aria-checked={view === "archived"} className={view === "archived" ? "is-selected" : ""} onClick={() => setQuery({ view: "archived" })}>{t("ws.archivedProjects")}</button></div><label className="compact-search"><span className="sr-only">{t("common.search")}</span><input value={q} placeholder={t("ws.searchProjects")} onChange={(event) => setQuery({ q: event.target.value })} /></label></div>
    {error && <InlineAlert tone="error" title={t("common.actionFailed")}>{error}</InlineAlert>}
    {list.status === "loading" && <Loading label={t("ws.loadingProjects")} />}{list.status === "error" && <EmptyState title={t("ws.projectsUnavailable")} hint={list.message} />}
    {list.status === "ready" && rows.length === 0 && <EmptyState title={q ? t("ws.noFilteredProjects") : view === "archived" ? t("ws.noArchivedProjects") : t("ws.noProjects")} hint={t("ws.createTopic")}>{q && <Button onClick={() => setQuery({ q: "" })}>{t("updates.clearFilters")}</Button>}</EmptyState>}
    <div className="operations-list">{rows.map((p) => <article className="operations-row project-row" key={p.id}><div className="operations-row-main"><div><div className="operations-row-title"><h2><a href={`/projects/${p.id}`} onClick={(event) => { event.preventDefault(); navigate(`/projects/${p.id}`); }}>{p.name}</a></h2>{p.pinned && <StatusBadge tone="normal">{t("ws.pinned")}</StatusBadge>}<StatusBadge tone={p.archived_at ? "unknown" : "positive"}>{p.archived_at ? t("ws.projectArchived") : t("ws.activeProjects")}</StatusBadge></div><p>{p.description || t("ws.projectDescription")}</p></div></div><dl className="operations-facts"><div><dt>{t("ws.curatedTrials")}</dt><dd>{p.counts.trials}</dd></div><div><dt>{t("ws.linkedMonitors")}</dt><dd>{p.counts.monitors}</dd></div><div><dt>{t("ws.savedSearches")}</dt><dd>{p.counts.saved_searches}</dd></div><div><dt>{t("ws.evidenceBookmarks")}</dt><dd>{p.counts.evidence}</dd></div><div><dt>{t("ws.notes")}</dt><dd>{p.counts.notes}</dd></div><div><dt>{t("ws.lastActivity", { date: "" })}</dt><dd>{p.last_activity ? absTime(p.last_activity) : "—"}</dd></div></dl><div className="operations-row-actions"><Button variant="primary" onClick={() => navigate(`/projects/${p.id}`)}>{t("ws.open")}</Button><ActionMenu label={t("common.moreActions")}><button role="menuitem" onClick={() => setEditor({ mode: "rename", project: p })}>{t("ws.rename")}</button><button role="menuitem" onClick={() => mutate(updateProject(p.id, { pinned: !p.pinned }))}>{p.pinned ? t("ws.unpin") : t("ws.pin")}</button><button role="menuitem" onClick={() => mutate(updateProject(p.id, { archived: !p.archived_at }))}>{p.archived_at ? t("ws.restore") : t("ws.archive")}</button><button role="menuitem" className="danger" onClick={() => setDeleting(p)}>{t("ws.delete")}</button></ActionMenu></div></article>)}</div>
    <ProjectEditor open={Boolean(editor)} mode={editor?.mode ?? "create"} initial={editor?.project} t={t} busy={busy} error={error} onClose={() => setEditor(null)} onSubmit={(name, description) => mutate(editor?.mode === "rename" && editor.project ? updateProject(editor.project.id, { name, description }) : createProject(name, description), () => setEditor(null))} />
    <ConfirmDialog open={Boolean(deleting)} title={t("ws.deleteProjectTitle", { name: deleting?.name ?? "" })} description={t("ws.deleteProjectConfirm", { name: deleting?.name ?? "" })} confirmLabel={t("ws.delete")} cancelLabel={t("common.cancel")} busy={busy} error={error} onClose={() => setDeleting(null)} onConfirm={() => deleting && mutate(deleteProject(deleting.id), () => setDeleting(null))} />
  </section>;
}

function ProjectEditor({ open, mode, initial, t, busy, error, onClose, onSubmit }: { open: boolean; mode: "create" | "rename"; initial?: ProjectListItem; t: Translate; busy: boolean; error: string; onClose: () => void; onSubmit: (name: string, description: string) => void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const identity = `${mode}:${initial?.id ?? 0}:${open}`; const last = useRef("");
  if (last.current !== identity) { last.current = identity; setName(initial?.name ?? ""); setDescription(initial?.description ?? ""); }
  return <Dialog open={open} title={mode === "create" ? t("ws.newProject") : t("ws.rename")} description={t("ws.projectEditorHint")} onClose={onClose}><form className="dialog-form" onSubmit={(event) => { event.preventDefault(); if (name.trim()) onSubmit(name.trim(), description.trim()); }}><label><span>{t("ws.projectName")}</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} maxLength={120} required /></label><label><span>{t("ws.projectDescriptionLabel")}</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={2000} /></label>{error && <div className="error-note" role="alert">{error}</div>}<footer className="ui-dialog-actions"><Button type="button" onClick={onClose}>{t("common.cancel")}</Button><Button type="submit" variant="primary" loading={busy} disabled={!name.trim()}>{mode === "create" ? t("ws.newProject") : t("mon.save")}</Button></footer></form></Dialog>;
}

function ProjectDetail({ id, t, lang }: { id: number; t: Translate; lang: Lang }) {
  const route = useRoute(); const tab = projectTab(route.query.get("tab")); const tview = parseTrialView(route.query.get("trial_view"));
  const trialPage = positivePage(route.query.get("trial_page")); const matchPage = positivePage(route.query.get("match_page")); const page = positivePage(route.query.get("page"));
  const windowValue = ["24h", "7d", "30d", "all"].includes(route.query.get("window") ?? "") ? route.query.get("window")! : "7d"; const severity = route.query.get("severity") ?? ""; const registry = route.query.get("registry") ?? ""; const category = route.query.get("category") ?? "";
  const [tick, setTick] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [dialog, setDialog] = useState<{ kind: "rename" | "note" | "evidence" | "delete-note" | "delete-evidence"; value?: string; id?: number; eventId?: number } | null>(null);
  const detail = useJson(`/api/projects/${id}?trial_page=${trialPage}&watched_only=${tview === "watched"}&refresh=${tick}`, isProjectDetail);
  const updates = useJson(["overview", "activity"].includes(tab) ? `/api/updates?scope=project&project_id=${id}&window=${windowValue}&page=${page}${severity ? `&severity=${severity}` : ""}${registry ? `&registry=${registry}` : ""}${category ? `&category=${encodeURIComponent(category)}` : ""}` : null, isUpdates);
  const briefing = useJson(["overview", "intelligence"].includes(tab) ? `/api/intelligence/briefing?scope=project&project_id=${id}&window=${windowValue === "all" ? "30d" : windowValue}&registry=${registry || "all"}` : null, isBriefing);
  const membership = useJson<Membership>(tab === "activity" && windowValue !== "all" ? `/api/intelligence/overview?scope=project&project_id=${id}&window=${windowValue}&registry=${registry || "all"}` : null, isMembership);
  const matches = useJson<MatchTrials>(tab === "trials" && tview === "matches" ? `/api/projects/${id}/monitor-trials?page=${matchPage}` : null, isMatchTrials);
  const updateUrl = (values: Record<string, string>) => { const next = new URLSearchParams(route.query); Object.entries(values).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); navigate(`/projects/${id}?${next}`); };
  const mutate = async (job: Promise<unknown>, after?: () => void) => { setBusy(true); setError(""); try { await job; setTick((v) => v + 1); after?.(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
  if (detail.status === "loading") return <section className="page-main"><Loading label={t("ws.loadingProject")} /></section>; if (detail.status === "error") return <section className="page-main"><EmptyState title={t("ws.projectUnavailable")} hint={detail.message} /></section>; if (detail.status !== "ready") return null;
  const p: Project = detail.data.project; const b = briefing.status === "ready" ? briefing.data : null; const eventRows = updates.status === "ready" ? updates.data.items : [];
  const openEvent = (e: { source: string; trial_id: string; event_id: number }) => navigate(`/trials/${encodeURIComponent(e.source)}/${encodeURIComponent(e.trial_id)}?tab=changes&event=${e.event_id}`);
  return <section className="page-main project-detail operations-page"><ScopeHeader t={t} eyebrow={t("ws.projectEyebrow")} title={p.name} description={p.description || t("ws.projectDescription")} meta={t("ws.projectMeta", { trials: p.counts.trials, memberships: p.monitors.reduce((n, m) => n + m.current_trials, 0), date: p.last_activity ?? "—" })} sources={p.freshness?.sources.map((s) => ({ name: s.full_name, freshness: s.freshness }))}><Button variant="quiet" onClick={() => navigate("/projects")}>← {t("ws.allProjects")}</Button><a className="ui-button ui-button-secondary" href={`/api/projects/${id}/export`} download={`project-${id}.md`}>{t("ws.exportMarkdown")}</a><ActionMenu label={t("common.moreActions")}><button role="menuitem" onClick={() => setDialog({ kind: "rename", value: p.name })}>{t("ws.rename")}</button><button role="menuitem" onClick={() => mutate(updateProject(id, { pinned: !p.pinned }))}>{p.pinned ? t("ws.unpin") : t("ws.pin")}</button><button role="menuitem" onClick={() => mutate(updateProject(id, { archived: !p.archived_at }))}>{p.archived_at ? t("ws.restore") : t("ws.archive")}</button></ActionMenu></ScopeHeader>
    {p.archived_at && <InlineAlert tone="info" title={t("ws.projectArchived")}>{t("ws.archivedNotice")}</InlineAlert>}
    <div className="page-tabs" role="tablist" aria-label={t("ws.projectViews")}>{TABS.map((value) => <button key={value} role="tab" aria-selected={tab === value} className={`ptab ${tab === value ? "ptab-on" : ""}`} onClick={() => updateUrl({ tab: value, page: "", severity: "", category: "", registry: "" })}>{t(`ws.${value}` as Parameters<Translate>[0])}</button>)}</div>{error && <InlineAlert tone="error" title={t("common.actionFailed")}>{error}</InlineAlert>}
    {tab === "overview" && <ProjectOverview p={p} b={b} events={eventRows} id={id} t={t} lang={lang} mutate={mutate} openEvent={openEvent} updateUrl={updateUrl} />}
    {tab === "trials" && <ProjectTrials p={p} id={id} t={t} view={tview} matches={matches} trialPage={trialPage} matchPage={matchPage} mutate={mutate} updateUrl={updateUrl} />}
    {tab === "activity" && <ProjectActivity updates={updates} membership={membership} t={t} lang={lang} filters={{ windowValue, severity, registry, category, page }} updateUrl={updateUrl} openEvent={openEvent} />}
    {tab === "intelligence" && <ProjectIntelligence briefing={briefing} t={t} updateUrl={updateUrl} openEvent={openEvent} />}
    {tab === "notebook" && <ProjectNotebook p={p} t={t} lang={lang} busy={busy} mutate={mutate} setDialog={setDialog} openEvent={openEvent} />}
    <TextEditor dialog={dialog} t={t} busy={busy} error={error} onClose={() => setDialog(null)} onSave={(value: string) => { if (!dialog) return; const job = dialog.kind === "rename" ? updateProject(id, { name: value }) : dialog.kind === "note" && dialog.id ? updateNote(id, dialog.id, value) : dialog.kind === "evidence" && dialog.eventId ? addEvidence(id, dialog.eventId, value) : null; if (job) mutate(job, () => setDialog(null)); }} />
    <ConfirmDialog open={dialog?.kind === "delete-note" || dialog?.kind === "delete-evidence"} title={dialog?.kind === "delete-note" ? t("ws.deleteNoteTitle") : t("ws.removeEvidenceTitle")} description={dialog?.kind === "delete-note" ? t("ws.deleteNoteConfirm") : t("ws.removeEvidenceConfirm")} confirmLabel={dialog?.kind === "delete-note" ? t("ws.delete") : t("ws.removeEvidence")} cancelLabel={t("common.cancel")} busy={busy} error={error} onClose={() => setDialog(null)} onConfirm={() => dialog?.kind === "delete-note" && dialog.id ? mutate(deleteNote(id, dialog.id), () => setDialog(null)) : dialog?.eventId && mutate(deleteEvidence(id, dialog.eventId), () => setDialog(null))} />
  </section>;
}

function ProjectOverview({ p, b, events, id, t, lang, mutate, openEvent: _openEvent }: any) { return <><IntelligenceMetricStrip items={[{ label: t("ws.curatedTrials"), value: p.counts.trials }, { label: t("ws.monitorMemberships"), value: p.monitors.reduce((n: number, m: any) => n + m.current_trials, 0) }, { label: t("ws.activeMonitors"), value: p.monitors.filter((m: any) => m.enabled).length }, { label: t("sev.critical"), value: b?.counts.critical_changes ?? "—", severity: "critical" }]} /><PageSection title={t("ws.researchSetup")}><div className="analysis-grid"><div><h3>{t("ws.savedSearches")}</h3><p className="form-hint">{t("ws.searchesPassive")}</p>{p.saved_searches.map((s: any) => <div className="operations-mini" key={s.id}><strong>{s.name}</strong><div><Button variant="quiet" onClick={() => { try { navigate(`/trials?${new URLSearchParams(searchStateToQuery(savedStateToSearchState(JSON.parse(s.state_json))))}&saved_search=${s.id}`); } catch { /* surfaced by invalid saved state elsewhere */ } }}>{t("ws.openSearch")}</Button><Button variant="quiet" onClick={() => mutate(removeAsset(id, "searches", s.id))}>{t("ws.remove")}</Button></div></div>)}{!p.saved_searches.length && <EmptyState title={t("ws.noLinkedSearches")} />}</div><div><h3>{t("ws.linkedMonitors")}</h3><p className="form-hint">{t("ws.monitorNote")}</p>{p.monitors.map((m: any) => <div className="operations-mini" key={m.id}><strong>{m.name}</strong><StatusBadge tone={m.enabled ? "positive" : "unknown"}>{m.enabled ? t("mon.active") : t("mon.paused")}</StatusBadge><div><Button variant="quiet" onClick={() => navigate(`/monitors/${m.id}`)}>{t("ws.openMonitor")}</Button><Button variant="quiet" onClick={() => mutate(removeAsset(id, "monitors", m.id))}>{t("ws.remove")}</Button></div></div>)}{!p.monitors.length && <EmptyState title={t("ws.noLinkedMonitors")} />}</div></div></PageSection><div className="analysis-grid"><PageSection title={t("ws.recentPriority")}>{events.filter((e: any) => ["critical", "important"].includes(e.severity)).slice(0, 5).map((e: any) => <ChangeRow key={e.event_id} item={e} t={t} lang={lang} />)}{!events.length && <EmptyState title={t("ws.noRecent")} />}</PageSection><PageSection title={t("ws.sourceFreshness")}>{b?.freshness.sources.map((s: any) => <div className="operations-mini" key={s.full_name}><strong>{s.full_name}</strong><FreshnessBadge t={t} freshness={s.freshness} /></div>) ?? <Loading label={t("ws.loadingBriefing")} />}</PageSection></div></>; }

function ProjectTrials({ p, id, t, view, matches, trialPage, matchPage, mutate, updateUrl }: any) { const rows = view === "matches" && matches.status === "ready" ? matches.data.trials : p.trials; return <section><div className="section-head"><h2>{t("ws.projectTrials")}</h2><div className="ui-segmented" role="radiogroup" aria-label={t("ws.projectTrials")}>{(["curated", "matches", "watched"] as const).map((value) => <button role="radio" aria-checked={view === value} className={view === value ? "is-selected" : ""} key={value} onClick={() => updateUrl({ trial_view: value, trial_page: "1", match_page: "1" })}>{t(`ws.trialView.${value}`)}</button>)}</div></div>{matches.status === "loading" && view === "matches" && <Loading label={t("ws.loadingMatches")} />}{matches.status === "error" && view === "matches" && <EmptyState title={t("ws.matchesUnavailable")} hint={matches.message} />}{rows.length === 0 && <EmptyState title={view === "matches" ? t("ws.noMatches") : view === "watched" ? t("ws.noWatchedCurated") : t("ws.noCurated")} /> }<div className="operations-list">{rows.map((r: any) => <article className="operations-row compact" key={sourceTrialKey(r.source, r.trial_id)}><div className="operations-row-main"><div><h3><a href={`/trials/${encodeURIComponent(r.source)}/${encodeURIComponent(r.trial_id)}`} onClick={(e) => { e.preventDefault(); navigate(`/trials/${encodeURIComponent(r.source)}/${encodeURIComponent(r.trial_id)}`); }}>{r.title || r.trial_id}</a></h3><small>{r.source}:{r.trial_id}{r.monitors?.length ? ` · ${r.monitors.join(", ")}` : ""}</small></div></div>{view !== "matches" && <div className="operations-row-actions"><StatusBadge tone={r.watching ? "positive" : "unknown"}>{r.watching ? t("trial.watching") : t("trial.unwatchLabel")}</StatusBadge><Button variant="quiet" onClick={() => mutate(removeAsset(id, "trials", r.trial_id, r.source))}>{t("ws.removeProject")}</Button></div>}</article>)}</div><div className="pagination"><Button disabled={(view === "matches" ? matchPage : trialPage) <= 1} onClick={() => updateUrl({ [view === "matches" ? "match_page" : "trial_page"]: String((view === "matches" ? matchPage : trialPage) - 1) })}>{t("ws.previous")}</Button><span>{t("ws.pagination", { page: view === "matches" ? matchPage : trialPage })}</span><Button disabled={view === "matches" ? matches.status !== "ready" || matchPage * matches.data.page_size >= matches.data.total : trialPage * p.trial_page_size >= (view === "watched" ? p.watched_trial_count : p.counts.trials)} onClick={() => updateUrl({ [view === "matches" ? "match_page" : "trial_page"]: String((view === "matches" ? matchPage : trialPage) + 1) })}>{t("ws.next")}</Button></div></section>; }

function ProjectActivity({ updates, membership, t, lang, filters, updateUrl }: any) { return <section><h2>{t("ws.projectActivity")}</h2><div className="operations-toolbar"><select aria-label={t("ws.time")} value={filters.windowValue} onChange={(e) => updateUrl({ window: e.target.value, page: "1" })}>{["24h", "7d", "30d", "all"].map((v) => <option key={v} value={v}>{v}</option>)}</select><select aria-label={t("ws.severity")} value={filters.severity} onChange={(e) => updateUrl({ severity: e.target.value, page: "1" })}><option value="">{t("ws.allSeverity")}</option><option value="priority">{t("ws.prioritySeverity")}</option>{["critical", "important", "normal", "minor"].map((v) => <option key={v} value={v}>{t(`sev.${v}`)}</option>)}</select><select aria-label={t("ws.registry")} value={filters.registry} onChange={(e) => updateUrl({ registry: e.target.value, page: "1" })}><option value="">{t("intel.allRegistries")}</option>{REGISTRY_OPTIONS.map((v) => <option key={v}>{v}</option>)}</select><select aria-label={t("ws.category")} value={filters.category} onChange={(e) => updateUrl({ category: e.target.value, page: "1" })}><option value="">{t("ws.allCategories")}</option>{["recruitment", "timeline", "outcomes", "enrollment", "sponsor", "geography", "intervention", "eligibility", "other"].map((v) => <option key={v} value={v}>{categoryLabel(v, t)}</option>)}</select></div>{updates.status === "loading" && <Loading label={t("ws.loadingUpdates")} />}{updates.status === "error" && <EmptyState title={t("ws.updatesUnavailable")} hint={updates.message} />}{updates.status === "ready" && <><IntelligenceMetricStrip items={[{ label: t("ws.changeEvents"), value: updates.data.total }, { label: t("ws.changedTrials"), value: updates.data.trial_count }, { label: t("sev.critical"), value: updates.data.facets.severities.critical ?? 0, severity: "critical" }, { label: t("sev.important"), value: updates.data.facets.severities.important ?? 0, severity: "important" }]} />{updates.data.analytics && <div className="analysis-grid"><PageSection title={t("ws.trend")}><ActivityTrend t={t} buckets={updates.data.analytics.trends} empty={t("ws.trend.empty")} /></PageSection><PageSection title={t("ws.categories")}><CategoryBreakdown t={t} categories={updates.data.analytics.categories} empty={t("ws.trend.empty")} /></PageSection></div>}<div className="intel-change-list">{updates.data.items.map((item: any) => <ChangeRow key={item.event_id} item={item} t={t} lang={lang} />)}</div></>}<PageSection title={t("ws.membershipActivity")}>{membership.status === "ready" && membership.data.monitor_activity.length ? membership.data.monitor_activity.map((event: any) => <div className="operations-mini" key={event.id}><strong>{t(`ws.membershipEvent.${event.event_type.replace("trial_", "")}`)}</strong><span>{event.trial_id} · {event.monitor_name}</span><small>{absTime(event.detected_at)}</small></div>) : <p>{t("ws.noMembership")}</p>}</PageSection></section>; }

function ProjectIntelligence({ briefing, t, updateUrl, openEvent }: any) { if (briefing.status === "loading") return <Loading label={t("ws.loadingBriefing")} />; if (briefing.status === "error") return <EmptyState title={t("ws.briefingUnavailable")} hint={briefing.message} />; const b = briefing.data; return <section><div className="section-head"><div><h2>{t("ws.projectIntelligence")}</h2><p className="eyebrow">{t("intel.executiveSummary")}</p></div><Button variant="secondary" onClick={() => updateUrl({ tab: "activity" })}>{t("ws.viewProjectActivity")}</Button></div><p className="reading-copy">{b.summary || t("intel.summaryTemplate", { new: b.counts.new_trials, changed: b.counts.changed_trials, events: b.counts.change_events, critical: b.counts.critical_changes, important: b.counts.important_changes, entered: b.counts.entered, left: b.counts.left })}</p><IntelligenceMetricStrip items={[{ label: t("sev.critical"), value: b.counts.critical_changes, severity: "critical" }, { label: t("sev.important"), value: b.counts.important_changes, severity: "important" }, { label: t("ws.changedTrials"), value: b.counts.changed_trials }, { label: t("dash.newTrials"), value: b.counts.new_trials }]} />{b.sections.map((section: any) => <PageSection key={section.key} title={`${t(`intel.section.${section.key}`)} · ${section.count}`}>{section.key === "priority" && section.items?.slice(0, 5).map((event: any) => <button className="analysis-row" key={event.event_id} onClick={() => openEvent(event)}><SeverityBadge severity={event.severity} t={t} /><span>{event.title}<small>{event.trial_id}</small></span></button>)}<Button variant="quiet" onClick={() => updateUrl({ tab: "activity", category: section.key === "priority" ? "" : section.key })}>{t("ws.viewRelated")} →</Button></PageSection>)}</section>; }

function ProjectNotebook({ p, t, lang, busy, mutate, setDialog, openEvent }: any) { const [note, setNote] = useState(""); return <section><InlineAlert tone="info" title={t("ws.notebook")}>{t("ws.notesDisclaimer")}</InlineAlert><div className="notebook-grid"><section><h2>{t("ws.notes")}</h2><form className="note-composer" onSubmit={(e) => { e.preventDefault(); if (note.trim()) mutate(addNote(p.id, note.trim()), () => setNote("")); }}><label><span>{t("ws.newNote")}</span><textarea value={note} onChange={(e) => setNote(e.target.value)} maxLength={10000} /></label><Button type="submit" variant="primary" loading={busy} disabled={!note.trim()}>{t("ws.addNote")}</Button></form>{!p.notes.length && <EmptyState title={t("ws.noNotes")} />}{p.notes.map((n: any) => <article className="notebook-entry" key={n.id}><p>{n.body}</p><small>{absTime(n.updated_at)}</small><div><Button variant="quiet" onClick={() => setDialog({ kind: "note", id: n.id, value: n.body })}>{t("ws.editNote")}</Button><Button variant="quiet" onClick={() => setDialog({ kind: "delete-note", id: n.id })}>{t("ws.delete")}</Button></div></article>)}</section><section><h2>{t("ws.evidenceBookmarks")}</h2>{!p.evidence.length && <EmptyState title={t("ws.noEvidence")} />}{p.evidence.map((e: any) => <article className="notebook-entry evidence-entry" key={e.id}><div><SeverityBadge severity={e.severity} t={t} /><button className="text-btn" onClick={() => openEvent(e)}>{e.title}</button></div><p><strong>{fieldLabel(e.field_name, lang)}</strong><br />{e.old_value || "—"} → {e.new_value || "—"}</p><small>{e.source}:{e.trial_id} · #{e.event_id}</small>{e.note && <blockquote>{e.note}</blockquote>}<div><Button variant="quiet" onClick={() => setDialog({ kind: "evidence", eventId: e.event_id, value: e.note })}>{t("ws.annotate")}</Button><Button variant="quiet" onClick={() => setDialog({ kind: "delete-evidence", eventId: e.event_id })}>{t("ws.removeEvidence")}</Button></div></article>)}</section></div></section>; }

function TextEditor({ dialog, p: _p, t, busy, error, onClose, onSave }: any) { const editable = dialog && ["rename", "note", "evidence"].includes(dialog.kind); const [value, setValue] = useState(""); const key = `${dialog?.kind}:${dialog?.id ?? dialog?.eventId ?? 0}:${dialog?.value ?? ""}`; const ref = useRef(""); if (ref.current !== key) { ref.current = key; setValue(dialog?.value ?? ""); } return <Dialog open={Boolean(editable)} title={dialog?.kind === "rename" ? t("ws.rename") : dialog?.kind === "note" ? t("ws.editNote") : t("ws.evidenceAnnotation")} onClose={onClose}><form className="dialog-form" onSubmit={(e) => { e.preventDefault(); if (dialog?.kind === "evidence" || value.trim()) onSave(value.trim()); }}>{dialog?.kind === "rename" ? <label><span>{t("ws.projectName")}</span><input autoFocus value={value} onChange={(e) => setValue(e.target.value)} maxLength={120} /></label> : <label><span>{dialog?.kind === "note" ? t("ws.editNote") : t("ws.evidenceAnnotation")}</span><textarea autoFocus value={value} onChange={(e) => setValue(e.target.value)} maxLength={10000} /></label>}{error && <div className="error-note" role="alert">{error}</div>}<footer className="ui-dialog-actions"><Button type="button" onClick={onClose}>{t("common.cancel")}</Button><Button type="submit" variant="primary" loading={busy}>{t("mon.save")}</Button></footer></form></Dialog>; }
